openapi: 3.0.0
info:
  title: Digital Wallet API
  version: 1.0.0
paths:
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
      responses:
        '201':
          description: User registered successfully
  /api/auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: Login successful
  /api/wallet/deposit:
    post:
      summary: Deposit funds to wallet
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Amount'
      responses:
        '200':
          description: Deposit successful
  /api/wallet/withdraw:
    post:
      summary: Withdraw funds from wallet
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Amount'
      responses:
        '200':
          description: Withdrawal successful
  /api/wallet/transfer:
    post:
      summary: Transfer funds to another user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transfer'
      responses:
        '200':
          description: Transfer successful
  /api/admin/transactions/flagged:
    get:
      summary: Get all flagged transactions
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of flagged transactions
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Register:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
    Login:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    Amount:
      type: object
      required:
        - amount
      properties:
        amount:
          type: number
    Transfer:
      type: object
      required:
        - recipientEmail
        - amount
      properties:
        recipientEmail:
          type: string
        amount:
          type: number
